#!/bin/sh
set -o pipefail

cd `dirname $0`

if [ $# -ge 2 ]; then
	source Configuration $1 $2
else
	source Configuration
fi

export DATATEST_DBSERVER DATATEST_DBNAME PYTHONPATH

date
./showSnpByID.py $1 2>&1 || exit 1;